In [1]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer
from sklearn.metrics import accuracy_score
from get_nice_text import *
import pandas as pd
import re
import numpy as np

In [2]:
df = get_nice_text()

In [3]:
cv = CountVectorizer()

In [4]:
df_count = cv.fit_transform(df)

In [5]:
trans = TfidfTransformer()

In [6]:
x = trans.fit_transform(df_count)

In [21]:
from sklearn.cluster import KMeans
model = KMeans()
lab_0 = model.fit_predict(x)

In [8]:
df_lab = pd.read_csv('./AllBooks_baseline_DTM_Labelled.csv')
names = list(df_lab.iloc[:,0])

All in one czy Vectorizer

In [30]:
vek = TfidfVectorizer(stop_words="english")
x = vek.fit_transform(df)

In [31]:
x

<590x8067 sparse matrix of type '<class 'numpy.float64'>'
	with 37960 stored elements in Compressed Sparse Row format>

wyciagnie labelsow poprawnych

In [13]:
labels = [re.match("^[a-zA-Z]+", n).group(0) for n in names]

In [14]:
lab

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 1, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 1, 6, 1, 3, 1, 1, 1, 6, 1, 1, 4, 6, 1, 1, 1, 1, 1, 5, 3, 1,
       1, 4, 1, 1, 1, 1, 1, 4, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 6, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 6, 1, 1, 6, 4, 4, 4, 4,
       4, 4, 4, 5, 7, 4, 5, 6, 4, 7, 4, 6, 4, 7, 4, 1, 1, 1, 7, 4, 7, 5,
       5, 1, 1, 1, 4, 5, 4, 4, 4, 5, 5, 5, 7, 5, 1, 4, 5, 4, 4, 4, 7, 4,
       7, 6, 4, 7, 4, 4, 4, 4, 4, 7, 6, 5, 4, 7, 7, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 1, 7, 4, 4, 4, 3, 4, 4, 4, 4, 4, 6, 5, 4, 4, 4, 4, 4,
       5, 4, 4, 6, 4, 7, 4, 4, 4, 4, 7, 4, 6, 5, 4, 4, 4, 4, 4, 1, 4, 7,
       4, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 6, 4, 4, 4, 1, 5, 5, 5, 5,
       4, 1, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 5,
       4, 4, 6, 6, 6, 6, 6, 3, 6, 6, 6, 6, 6, 6, 6,

In [15]:
model = KMeans(n_clusters=8)
lab = model.fit_predict(x)

In [16]:
lab

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 6, 6, 2,
       6, 6, 6, 0, 6, 6, 0, 6, 6, 4, 6, 2, 6, 4, 6, 6, 6, 6, 6, 4, 6, 4,
       6, 4, 4, 6, 6, 6, 7, 6, 6, 6, 6, 6, 4, 6, 6, 6, 4, 6, 6, 6, 6, 6,
       4, 4, 6, 6, 6, 6, 6, 6, 6, 2, 7, 7, 7, 0, 4, 6, 4, 6, 6, 6, 6, 7,
       6, 6, 6, 6, 4, 0, 6, 6, 6, 6, 6, 6, 6, 7, 6, 4, 6, 6, 6, 0, 0, 0,
       4, 6, 6, 6, 6, 6, 6, 0, 6, 6, 0, 6, 2, 7, 6, 6, 6, 6, 6, 4, 7, 2,
       7, 6, 2, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7,
       6, 2, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6,
       6, 7, 3, 3, 3, 3, 2, 3, 2, 2, 2, 3, 2, 3, 2,

In [25]:
from sklearn.metrics.cluster import homogeneity_score, completeness_score, v_measure_score
print("homogeneity_score = {}".format(homogeneity_score(labels, lab)))
print("completeness_score = {}".format(completeness_score(labels, lab)))
print("v_measure_score = {}".format(v_measure_score(labels, lab)))

homogeneity_score = 0.6208471880011318
completeness_score = 0.5427691357174474
v_measure_score = 0.579188663436935


In [32]:
# zobaczmy czy bez stpo words
vek = TfidfVectorizer()
x = vek.fit_transform(df)
model = KMeans(n_clusters=8)
lab = model.fit_predict(x)
print("homogeneity_score = {}".format(homogeneity_score(labels, lab)))
print("completeness_score = {}".format(completeness_score(labels, lab)))
print("v_measure_score = {}".format(v_measure_score(labels, lab)))

homogeneity_score = 0.44995984036384673
completeness_score = 0.508016242912445
v_measure_score = 0.4772288401634297


Inny model

In [101]:
xx = x.todense() != 0

In [115]:
xx = xx.reshape(1,4923550)

In [122]:
x.todense().reshape(1,4923550)[xx]

matrix([[0.02191023, 0.24199403, 0.39972823, ..., 0.027298  , 0.03386059,
         0.06222781]])