In [104]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer
from sklearn.metrics import accuracy_score
from get_nice_text import *
import pandas as pd
import re
import numpy as np

In [4]:
df = get_nice_text()

In [6]:
cv = CountVectorizer()

In [123]:
df_count = cv.fit_transform(df)

In [11]:
trans = TfidfTransformer()

In [13]:
x = trans.fit_transform(df_count)

In [17]:
from sklearn.cluster import KMeans
model = KMeans()
lab = model.fit_predict(x)

In [29]:
df_lab = pd.read_csv('./AllBooks_baseline_DTM_Labelled.csv')
names = list(df_lab.iloc[:,0])

All in one czy Vectorizer

In [82]:
vek = TfidfVectorizer()
x = vek.fit_transform(df)

wyciagnie labelsow poprawnych

In [78]:
labels = [re.match("^[a-zA-Z]+", n).group(0) for n in names]

In [90]:
lab

array([4, 7, 7, 7, 7, 3, 3, 3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 4,
       0, 7, 7, 0, 3, 3, 3, 3, 0, 7, 7, 3, 3, 4, 7, 7, 7, 0, 3, 7, 1, 7,
       7, 7, 7, 5, 4, 4, 4, 7, 4, 7, 4, 4, 4, 7, 4, 4, 4, 4, 4, 7, 7, 7,
       4, 3, 4, 4, 4, 4, 4, 7, 4, 4, 7, 4, 4, 4, 7, 4, 4, 4, 4, 7, 4, 4,
       7, 4, 7, 7, 4, 4, 4, 7, 4, 6, 4, 7, 4, 4, 7, 7, 7, 4, 7, 4, 4, 4,
       4, 4, 7, 4, 3, 4, 4, 4, 4, 4, 4, 7, 4, 4, 7, 4, 4, 5, 7, 7, 3, 4,
       3, 3, 3, 3, 1, 7, 3, 1, 7, 7, 7, 7, 7, 3, 7, 4, 4, 7, 0, 7, 0, 0,
       0, 0, 7, 4, 7, 0, 7, 7, 7, 0, 0, 1, 0, 7, 4, 7, 1, 7, 3, 7, 0, 7,
       7, 4, 1, 1, 1, 7, 7, 7, 7, 0, 7, 3, 7, 0, 0, 3, 4, 3, 4, 3, 7, 7,
       3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 7, 3, 7, 3, 7, 1, 3, 3, 7, 7, 7,
       3, 3, 7, 7, 3, 7, 3, 7, 3, 3, 1, 7, 7, 3, 0, 0, 3, 3, 3, 0, 7, 7,
       7, 7, 7, 3, 3, 3, 3, 3, 3, 1, 7, 7, 3, 7, 7, 7, 5, 1, 1, 1, 1, 1,
       1, 4, 4, 3, 7, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 7, 7, 7, 7, 1,
       3, 7, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 5, 5, 7,

In [83]:
model = KMeans(n_clusters=8)
lab = model.fit_predict(x)

In [91]:
lab

array([4, 7, 7, 7, 7, 3, 3, 3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 4,
       0, 7, 7, 0, 3, 3, 3, 3, 0, 7, 7, 3, 3, 4, 7, 7, 7, 0, 3, 7, 1, 7,
       7, 7, 7, 5, 4, 4, 4, 7, 4, 7, 4, 4, 4, 7, 4, 4, 4, 4, 4, 7, 7, 7,
       4, 3, 4, 4, 4, 4, 4, 7, 4, 4, 7, 4, 4, 4, 7, 4, 4, 4, 4, 7, 4, 4,
       7, 4, 7, 7, 4, 4, 4, 7, 4, 6, 4, 7, 4, 4, 7, 7, 7, 4, 7, 4, 4, 4,
       4, 4, 7, 4, 3, 4, 4, 4, 4, 4, 4, 7, 4, 4, 7, 4, 4, 5, 7, 7, 3, 4,
       3, 3, 3, 3, 1, 7, 3, 1, 7, 7, 7, 7, 7, 3, 7, 4, 4, 7, 0, 7, 0, 0,
       0, 0, 7, 4, 7, 0, 7, 7, 7, 0, 0, 1, 0, 7, 4, 7, 1, 7, 3, 7, 0, 7,
       7, 4, 1, 1, 1, 7, 7, 7, 7, 0, 7, 3, 7, 0, 0, 3, 4, 3, 4, 3, 7, 7,
       3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 7, 3, 7, 3, 7, 1, 3, 3, 7, 7, 7,
       3, 3, 7, 7, 3, 7, 3, 7, 3, 3, 1, 7, 7, 3, 0, 0, 3, 3, 3, 0, 7, 7,
       7, 7, 7, 3, 3, 3, 3, 3, 3, 1, 7, 7, 3, 7, 7, 7, 5, 1, 1, 1, 1, 1,
       1, 4, 4, 3, 7, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 7, 7, 7, 7, 1,
       3, 7, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 5, 5, 7,

Inny model

In [101]:
xx = x.todense() != 0

In [115]:
xx = xx.reshape(1,4923550)

In [122]:
x.todense().reshape(1,4923550)[xx]

matrix([[0.02191023, 0.24199403, 0.39972823, ..., 0.027298  , 0.03386059,
         0.06222781]])